/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelform;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import travelmodel.database_connect;
import travelmodel.delete_all_kendaraan;
import travelmodel.delete_all_kereta;
import travelmodel.delete_all_pesawat;
import travelmodel.update_koneksi;

/**
 *
 * @author Indra F
 */
public class update_all_kendaraan extends javax.swing.JFrame {

    /**
     * Creates new form delete_all_kendaraan
     */
    delete_all_kendaraan kendaraan = new delete_all_kendaraan();
    delete_all_pesawat pesawat = new delete_all_pesawat();
    delete_all_kereta kereta = new delete_all_kereta();
    
    public update_all_kendaraan() {
        initComponents();
        tabelkereta();
        tabelpesawat();
        tabelkendaraan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        id_bus = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_kendaraan = new javax.swing.JTable();
        nama_bus = new javax.swing.JTextField();
        asal_bus = new javax.swing.JTextField();
        tujuan_bus = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        delete_button = new javax.swing.JButton();
        update_bus = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        id_kereta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_kereta = new javax.swing.JTable();
        nama_kereta = new javax.swing.JTextField();
        asal_kereta = new javax.swing.JTextField();
        tujuan_kereta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        delete_kereta = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        id_maskapai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pesawat_table = new javax.swing.JTable();
        nama_maskapai = new javax.swing.JTextField();
        asal_maskapai = new javax.swing.JTextField();
        tujuan_maskapai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        delete_pesawat = new javax.swing.JButton();
        update_pesawat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LOGOUT_ADMIN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menu_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRAVELpedia.");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png")).getImage());

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(800, 350));
        jInternalFrame1.setVisible(true);

        tabel_kendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Merk", "Asal", "Tujuan"
            }
        ));
        tabel_kendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kendaraanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_kendaraan);

        nama_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_busActionPerformed(evt);
            }
        });

        delete_button.setText("DELETE");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_bus.setText("UPDATE");
        update_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_busActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(delete_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_bus))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_button)
                    .addComponent(update_bus))
                .addGap(0, 104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tujuan_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(asal_bus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_bus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_bus, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(id_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asal_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tujuan_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BUS", jInternalFrame1);

        jInternalFrame3.setVisible(true);

        id_kereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_keretaActionPerformed(evt);
            }
        });

        tabel_data_kereta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        tabel_data_kereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama Kereta", "Asal", "Tujuan"
            }
        ));
        tabel_data_kereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_data_keretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data_kereta);

        delete_kereta.setText("DELETE");
        delete_kereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_keretaActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(delete_kereta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(update))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_kereta)
                    .addComponent(update))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nama_kereta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_kereta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asal_kereta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tujuan_kereta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(id_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asal_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tujuan_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("KERETA", jInternalFrame3);

        jInternalFrame2.setVisible(true);

        pesawat_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Boeing", "Maskapai", "Asal", "Tujuan"
            }
        ));
        pesawat_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesawat_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pesawat_table);

        delete_pesawat.setText("DELETE");
        delete_pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_pesawatActionPerformed(evt);
            }
        });

        update_pesawat.setText("UPDATE");
        update_pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_pesawatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(delete_pesawat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_pesawat))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_pesawat)
                    .addComponent(update_pesawat))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama_maskapai, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(asal_maskapai)
                    .addComponent(tujuan_maskapai)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_maskapai))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(id_maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asal_maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tujuan_maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PESAWAT", jInternalFrame2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/updateanddelete.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LOGOUT_ADMIN.setBackground(new java.awt.Color(0, 153, 153));
        LOGOUT_ADMIN.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        LOGOUT_ADMIN.setForeground(new java.awt.Color(0, 153, 153));
        LOGOUT_ADMIN.setText("LOGOUT");
        LOGOUT_ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_ADMINActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel5.setText("here,you can update and delete data from database.");

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setForeground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Only admin can access this page.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menu_button.setText("MENU");
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT_ADMIN))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_button)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LOGOUT_ADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(id_kereta.getText() == "bedit"){
        id_kereta.requestFocus();
        }
        else{
            String kereta = id_kereta.getText();
            String namakereta = nama_kereta.getText();
            String asal_kota = asal_kereta.getText();
            String kota_tujuan = tujuan_kereta.getText();
            
            try{
                Statement statement = (Statement) update_koneksi.getConnection().createStatement();
                statement.executeUpdate("update kereta SET id_kereta='"+kereta+"',"+"nama_kereta='"+namakereta+"',"+"asal_kota1='"+asal_kota+"',"+"kota_tujuan='"+kota_tujuan+"'" + "WHERE id_kereta = '"+kereta+"' OR nama_kereta = '"+namakereta+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            }
            catch (Exception t){
                JOptionPane.showMessageDialog(null, "Data Gagal diubah");
            }
        }
        this.setVisible(false);
        update_all_kendaraan update = new update_all_kendaraan();
        update.setVisible(true);           

    }//GEN-LAST:event_updateActionPerformed

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        admin_menu delete = new admin_menu();
        delete.setVisible(true);
    }//GEN-LAST:event_menu_buttonActionPerformed

    private void pesawat_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesawat_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)pesawat_table.getModel();
        int selectedRow = pesawat_table.getSelectedRow();
        id_maskapai.setText(model.getValueAt(selectedRow, 0).toString());
        nama_maskapai.setText(model.getValueAt(selectedRow, 1).toString());
        asal_maskapai.setText(model.getValueAt(selectedRow, 2).toString());
        tujuan_maskapai.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_pesawat_tableMouseClicked

    private void update_pesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_pesawatActionPerformed
        // TODO add your handling code here:
        if(id_maskapai.getText() == "bedit"){
        id_maskapai.requestFocus();
        }else{
            String pesawat = id_maskapai.getText();
            String namapesawat = nama_maskapai.getText();
            String asal_pesawat = asal_maskapai.getText();
            String kota_pesawat = tujuan_maskapai.getText();
            
        try{
            Statement statement = (Statement) update_koneksi.getConnection().createStatement();
            statement.executeUpdate("update pesawat SET id_pesawat='"+pesawat+"',"+"nama_maskapai='"+namapesawat+"',"+"asal_kota='"+asal_pesawat+"',"+"tujuan_kota='"+kota_pesawat+"'" + "WHERE id_pesawat = '"+pesawat+"' OR nama_maskapai = '"+namapesawat+"'");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah");
        }
        }
        this.setVisible(false);
        update_all_kendaraan update = new update_all_kendaraan();
        update.setVisible(true);  
    }//GEN-LAST:event_update_pesawatActionPerformed

    private void update_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_busActionPerformed
        // TODO add your handling code here:
        if(id_bus.getText() == "bedit"){
        id_bus.requestFocus();
        }else{
            String kendaraan = id_bus.getText();
            String namabus = nama_bus.getText();
            String asalbus = asal_bus.getText();
            String kotabus = tujuan_bus.getText();
            
        try{
            Statement statement = (Statement) update_koneksi.getConnection().createStatement();
            statement.executeUpdate("update kendaraan SET id='"+kendaraan+"',"+"merk_kendaraan='"+namabus+"',"+"asal_kendaraan='"+asalbus+"',"+"tujuan_kendaraan='"+kotabus+"'" + "WHERE id = '"+kendaraan+"' OR merk_kendaraan = '"+namabus+"'");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah");
        }
        }
        this.setVisible(false);
        update_all_kendaraan update = new update_all_kendaraan();
        update.setVisible(true); 
    }//GEN-LAST:event_update_busActionPerformed

    private void tabel_kendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kendaraanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabel_kendaraan.getModel();
        int selectedRow = tabel_kendaraan.getSelectedRow();
        id_bus.setText(model.getValueAt(selectedRow, 0).toString());
        nama_bus.setText(model.getValueAt(selectedRow, 1).toString());
        asal_bus.setText(model.getValueAt(selectedRow, 2).toString());
        tujuan_bus.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tabel_kendaraanMouseClicked

    private void nama_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_busActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        String id = id_bus.getText();
        String nama_kendaraan = nama_bus.getText();
        
        if(kendaraan.hapus_kendaraan(id)){
            JOptionPane.showMessageDialog(rootPane,"Hapus kendaraan Berhasil");
            this.setVisible(false);
            update_all_kendaraan kendaraan = new update_all_kendaraan();
            kendaraan.setVisible(true);
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void delete_pesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_pesawatActionPerformed
        // TODO add your handling code here:
        String id = id_maskapai.getText();
        String nama_pesawat = nama_maskapai.getText();
        if(pesawat.hapus_pesawat(id)){
            JOptionPane.showMessageDialog(rootPane,"Hapus kendaraan Berhasil");
            this.setVisible(false);
            update_all_kendaraan kendaraan = new update_all_kendaraan();
            kendaraan.setVisible(true);
        }
        
    }//GEN-LAST:event_delete_pesawatActionPerformed

    private void delete_keretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_keretaActionPerformed
        // TODO add your handling code here:
        String idk = id_kereta.getText();
        String nama_kkereta = nama_kereta.getText();
        if(kereta.hapus_kereta(idk)){
            JOptionPane.showMessageDialog(rootPane,"Hapus kendaraan Berhasil");
            this.setVisible(false);
           update_all_kendaraan kendaraan = new update_all_kendaraan();
            kendaraan.setVisible(true);
        }
    }//GEN-LAST:event_delete_keretaActionPerformed

    private void LOGOUT_ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_ADMINActionPerformed
           this.setVisible(false);
        login kembali = new login();
        kembali.setVisible(true);
    }//GEN-LAST:event_LOGOUT_ADMINActionPerformed

    private void id_keretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_keretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_keretaActionPerformed

    private void tabel_data_keretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_data_keretaMouseClicked
        DefaultTableModel model = (DefaultTableModel)tabel_data_kereta.getModel();
        int selectedRow = tabel_data_kereta.getSelectedRow();
        id_kereta.setText(model.getValueAt(selectedRow, 0).toString());
        nama_kereta.setText(model.getValueAt(selectedRow, 1).toString());
        asal_kereta.setText(model.getValueAt(selectedRow, 2).toString());
        tujuan_kereta.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tabel_data_keretaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_all_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_all_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_all_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_all_kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_all_kendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGOUT_ADMIN;
    private javax.swing.JTextField asal_bus;
    private javax.swing.JTextField asal_kereta;
    private javax.swing.JTextField asal_maskapai;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton delete_kereta;
    private javax.swing.JButton delete_pesawat;
    private javax.swing.JTextField id_bus;
    private javax.swing.JTextField id_kereta;
    private javax.swing.JTextField id_maskapai;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton menu_button;
    private javax.swing.JTextField nama_bus;
    private javax.swing.JTextField nama_kereta;
    private javax.swing.JTextField nama_maskapai;
    private javax.swing.JTable pesawat_table;
    private javax.swing.JTable tabel_data_kereta;
    private javax.swing.JTable tabel_kendaraan;
    private javax.swing.JTextField tujuan_bus;
    private javax.swing.JTextField tujuan_kereta;
    private javax.swing.JTextField tujuan_maskapai;
    private javax.swing.JButton update;
    private javax.swing.JButton update_bus;
    private javax.swing.JButton update_pesawat;
    // End of variables declaration//GEN-END:variables

    public void  tabelkereta(){{
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Kereta");
        tabel.addColumn("Nama Kereta");
        tabel.addColumn("Kota Asal");
        tabel.addColumn("Kota Tujuan");
        tabel.addColumn("Waktu");

        try{
        Connection koneksi = new database_connect().condb();
        String sql = "select * from kereta order by id_kereta";
        Statement stat = koneksi.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
        }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
            tabel_data_kereta.setModel(tabel);
        }

    }
    
    public void  tabelpesawat(){{
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID pesawat");
    tabel.addColumn("Nama Maskapai");
    tabel.addColumn("Kota asal");
    tabel.addColumn("Kota Tujuan");
    tabel.addColumn("Waktu");

        try{
        Connection koneksi = new database_connect().condb();
        String sql = "select * from pesawat order by id_pesawat";
        Statement stat = koneksi.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
        }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
            pesawat_table.setModel(tabel);
        }

    }
    
    
    public void  tabelkendaraan(){{
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID kendaraan");
    tabel.addColumn("Nama Travel");
    tabel.addColumn("Asal");
    tabel.addColumn("Tujuan");
    tabel.addColumn("Waktu Berangkat");
    
        try{
        Connection koneksi = new database_connect().condb();
        String sql = "select * from kendaraan order by id";
        Statement stat = koneksi.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
    }
        tabel_kendaraan.setModel(tabel);
        }

    }
    
}
